const productArr = [
    {
        id: 1,
        name: "Kính Gentle Monkey Benven 01",
        category: "Kính Thời Trang",
        image: ["../img/prod1.webp", "../img/prod1-1.webp",
            "../img/prod1-2.webp", "../img/prod1-3.webp", "../img/prod1-4.webp"],
        price: "6.790.000",
        frameColor: "Đen",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 2,
        name: "Kính Gentle Monkey Bandoneon.S 01",
        category: "Kính Thời Trang",
        image: ["../img/prod2.webp", "../img/prod2-1.webp",
            "../img/prod2-2.webp", "../img/prod2-3.webp", "../img/prod2-4.webp"],
        price: "8.090.000",
        frameColor: "Đen",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 3,
        name: "Kính Gentle Monkey Benven CR7",
        category: "Kính Thời Trang",
        image: ["../img/prod3.webp", "../img/prod3-1.webp",
            "../img/prod3-2.webp", "../img/prod3-3.webp", "../img/prod3-4.webp"],
        price: "6.790.000",
        frameColor: "Xanh lá",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 4,
        name: "Kính Gentle Monkey Braid M01",
        category: "Kính Thời Trang",
        image: ["../img/prod4.jpg", "../img/prod4-1.jpg",
            "../img/prod4-2.jpg", "../img/prod4-3.jpg", "../img/prod4-4.jpg"],
        price: "7.690.000",
        frameColor: "Đen",
        lensColor: "Tím Gradient",
        material: "Titan",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 5,
        name: "Kính Gentle Monkey Gelati MG4",
        category: "Kính Thời Trang",
        image: ["../img/prod5.webp", "../img/prod5-1.webp",
            "../img/prod5-2.webp", "../img/prod5-3.webp", "../img/prod5-4.webp"],
        price: "7.390.000",
        frameColor: "Jelly sweets xanh, cam, đỏ gradient",
        lensColor: "Đỏ cam",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 6,
        name: "Kính Gentle Monkey Nada WC3",
        category: "Kính Thời Trang",
        image: ["../img/prod6.jpg", "../img/prod6-1.jpg",
            "../img/prod6-2.jpg", "../img/prod6-3.jpg", "../img/prod6-4.jpg"],
        price: "5.790.000",
        frameColor: "Trắng hồng và nâu",
        lensColor: "Hồng Gradient",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 7,
        name: "Kính Gentle Monkey Rosy 01",
        category: "Kính Thời Trang",
        image: ["../img/prod7.webp", "../img/prod7-1.jpg",
            "../img/prod7-2.jpg", "../img/prod7-3.jpg", "../img/prod7-4.jpg"],
        price: "5.590.000",
        frameColor: "Đen",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 8,
        name: "Kính Gentle Monkey Tambu YC6",
        category: "Kính Thời Trang",
        image: ["../img/prod8.jpg", "../img/prod8-1.jpg",
            "../img/prod8-2.jpg", "../img/prod8-3.jpg"],
        price: "6.490.000",
        frameColor: "Gold",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 9,
        name: "Kính Gentle Monkey Umber BLC7",
        category: "Kính Thời Trang",
        image: ["../img/prod9.webp", "../img/prod9-1.webp",
            "../img/prod9-2.webp", "../img/prod9-3.webp", "../img/prod9-4.webp"],
        price: "7.690.000",
        frameColor: "Xanh",
        lensColor: "Cam",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 10,
        name: "Kính Gentle Monkey Vis Viva BL2",
        category: "Kính Thời Trang",
        image: ["../img/prod10.jpg", "../img/prod10-1.jpg",
            "../img/prod10-2.jpg", "../img/prod10-3.jpg", "../img/prod10-4.jpg"],
        price: "6.790.000",
        frameColor: "Xanh",
        lensColor: "Xanh",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 11,
        name: "Kính Gentle Monkey Aba 02",
        category: "Kính Cận",
        image: ["../img/prod11.webp", "../img/prod11-1.webp",
            "../img/prod11-2.webp", "../img/prod11-3.webp", "../img/prod11-4.webp"],
        price: "7.890.000",
        frameColor: "Bạc",
        lensColor: "Trong suốt",
        material: "Titan",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 12,
        name: "Kính Gentle Monkey Academya 02",
        category: "Kính Cận",
        image: ["../img/prod12.webp", "../img/prod12-1.webp",
            "../img/prod12-2.webp", "../img/prod12-3.webp"],
        price: "7.890.000",
        frameColor: "Bạc",
        lensColor: "Trong suốt",
        material: "Titan",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 13,
        name: "Kính Gentle Monkey Ata 01",
        category: "Kính Cận",
        image: ["../img/prod13.webp", "../img/prod13-1.webp",
            "../img/prod13-2.webp", "../img/prod13-3.webp", "../img/prod13-4.webp"],
        price: "5.190.000",
        frameColor: "Đen",
        lensColor: "Trong suốt",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 14,
        name: "Kính Gentle Monkey GG0813O 001",
        category: "Kính Cận",
        image: ["../img/prod14.jpg", "../img/prod14-1.jpg",
            "../img/prod14-2.jpg", "../img/prod14-3.jpg", "../img/prod14-4.jpg"],
        price: "4.300.000",
        frameColor: "Đen",
        lensColor: "Trong suốt",
        material: "Nhựa",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 15,
        name: "Kính Gentle Monkey Loopy L1",
        category: "Kính Cận",
        image: ["../img/prod15.webp", "../img/prod15-1.webp",
            "../img/prod15-2.webp", "../img/prod15-3.webp"],
        price: "5.590.000",
        frameColor: "Đỏ cam",
        lensColor: "Cam Gradient",
        material: "Nhựa Acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 16,
        name: "Kính Gentle Monkey D’heygere Tiara 02",
        category: "Kính Cận",
        image: ["../img/prod16.webp", "../img/prod16-1.webp",
            "../img/prod16-2.webp", "../img/prod16-3.webp", "../img/prod16-4.webp",
            "../img/prod16-5.webp"],
        price: "23.090.000",
        frameColor: "Bạc",
        lensColor: "Trong suốt",
        material: "Titan",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 17,
        name: "Kính Gentle Monkey Rob KC1",
        category: "Kính Cận",
        image: ["../img/prod17.webp", "../img/prod17-1.webp",
            "../img/prod17-2.webp", "../img/prod17-3.webp", "../img/prod17-4.webp"],
        price: "7.190.000",
        frameColor: "Nâu và bạc",
        lensColor: "Trong suốt",
        material: "Nhựa acetate và Titan",
        function: "Chống tia UVA/UVB tới 99,9%"
    },
    {
        id: 18,
        name: "Kính Gentle Monkey Rob KC1",
        category: "Kính Cận",
        image: ["../img/prod18.webp", "../img/prod18-1.webp",
            "../img/prod18-2.webp", "../img/prod18-3.webp", "../img/prod18-4.webp"],
        price: "7.090.000",
        frameColor: "Xám trong & Bạc",
        lensColor: "Trong suốt",
        material: "Nhựa acetate & Titan",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 19,
        name: "Kính Gentle Monkey CL40104I Trắng",
        category: "Kính Râm",
        image: ["../img/prod19.webp", "../img/prod19-1.webp",
            "../img/prod19-2.webp", "../img/prod19-3.webp"],
        price: "5.990.000",
        frameColor: "Trắng",
        lensColor: "Khói",
        material: "Nhựa acetate",
        function: "Chống 99.9% tia UV"
    },
    {
        id: 20,
        name: "Kính Gentle Monkey Swift Oval Đen",
        category: "Kính Râm",
        image: ["../img/prod20.webp", "../img/prod20-1.webp",
            "../img/prod20-2.webp", "../img/prod20-3.webp", "../img/prod20-4.webp", "../img/prod20-5.webp"],
        price: "6.390.000",
        frameColor: "Đen",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống tia UVA/UVB tới 100%"
    },
    {
        id: 21,
        name: "Kính Gentle Monkey Swift Oval Đen",
        category: "Kính Râm",
        image: ["../img/prod21.webp", "../img/prod21-1.webp",
            "../img/prod21-2.webp", "../img/prod21-3.webp", "../img/prod21-4.webp", "../img/prod21-5.webp"],
        price: "8.390.000",
        frameColor: "Vàng",
        lensColor: "Xanh",
        material: "Titanium",
        function: "Chống 99.9% tia UV"
    },
    {
        id: 22,
        name: "Kính Gentle Monkey Swift Oval Đen",
        category: "Kính Râm",
        image: ["../img/prod22.webp", "../img/prod22-1.jpg",
            "../img/prod22-2.jpg", "../img/prod22-3.jpg", "../img/prod22-4.jpg"],
        price: "5.690.000",
        frameColor: "Đen",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 23,
        name: "Kính Gentle Monkey Swift Oval Đen",
        category: "Kính Râm",
        image: ["../img/prod23.jpg", "../img/prod23-1.jpg",
            "../img/prod23-2.jpg", "../img/prod23-3.jpg", "../img/prod23-4.jpg", "../img/prod23-5.jpg"],
        price: "6.190.000",
        frameColor: "Đen",
        lensColor: "Đen",
        material: "Nhựa acetate",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 24,
        name: "Kính Gentle Monkey Zodiac 02(Y)",
        category: "Kính Râm",
        image: ["../img/prod24.webp", "../img/prod24-1.webp",
            "../img/prod24-2.webp", "../img/prod24-3.webp", "../img/prod24-4.webp"],
        price: "8.590.000",
        frameColor: "Đen",
        lensColor: "Vàng",
        material: "Titan",
        function: "Chống ánh sáng xanh, tia cực tím 99.9%"
    },
    {
        id: 25,
        name: "Kính Gentle Monkey Austin Đồi Mồi",
        category: "Kính Râm",
        image: ["../img/prod25.webp", "../img/prod25-1.webp",
            "../img/prod25-2.webp", "../img/prod25-3.webp", "../img/prod25-4.webp"],
        price: "8.590.000",
        frameColor: "Đồi mồi",
        lensColor: "Nâu",
        material: "Acetate",
        function: "Chống tia UVA/UVB tới 99,9%"
    }
];

export default productArr;